
[colors]
draw_bold_text_with_bright_colors = false

[colors.normal]
black = "#2d2a2e"
blue = "#fc9867"
cyan = "#78dce8"
green = "#a9dc76"
magenta = "#ab9df2"
red = "#ff6188"
white = "#fcfcfa"
yellow = "#ffd866"

[colors.primary]
background = "#2d2a2e"
foreground = "#fcfcfa"

[cursor]
style = "Beam"

[font]
size = 9.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[selection]
save_to_clipboard = false

[terminal.shell]
program = "zellij"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
# opacity = 0.98

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true

[terminal]
